In [19]:
#1
#a
!python --version
#b
import torch
#c
torch.cuda.is_available() # 맥북 이슈로 난 cuda가 되지 않는다.

Python 3.11.7


False

In [21]:
a = torch.ones(3,3)

In [23]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
b = torch.ones(3,3)

In [27]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
a+b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [31]:
a = a.to('cuda')
b = b.to('cuda')
a + b

AssertionError: Torch not compiled with CUDA enabled