#### 텐서 기본 
생성 및 읽어오기

In [1]:
a = [1.0, 2.0, 3.0]

a[0], a[1], a[2], a

(1.0, 2.0, 3.0, [1.0, 2.0, 3.0])

In [5]:
import torch

a = torch.ones(3) # 크기가 3인 1차원 텐서, 값은 모두 1
a

tensor([1., 1., 1.])

In [13]:
a[0], a[1], a[2]

(tensor(1.), tensor(1.), tensor(1.))

In [15]:
a[2]=3
a

tensor([1., 1., 3.])

In [17]:
points = torch.zeros(6)

points[0] = 3
points[1] = 2
points[2] = 0.0
points[3] = 2.0
points[4] = 1
points[5] = 4.0

points

tensor([3., 2., 0., 2., 1., 4.])

In [23]:
float(points[2]), float(points[3])

(0.0, 2.0)

In [25]:
mylist = [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]

points = torch.tensor(mylist)
points

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [27]:
points.shape

torch.Size([3, 2])

In [31]:
points[0]

tensor([1., 2.])

In [54]:
points[1,0]

tensor(3.)

#### 인덱싱

In [40]:
points[:]

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [42]:
points[1:]

tensor([[3., 4.],
        [5., 6.]])

In [48]:
points[:, :1]

tensor([[1.],
        [3.],
        [5.]])

In [50]:
points[:, 0]

tensor([1., 3., 5.])

In [52]:
points[None] # unsqueeze와 동일하다고 함

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]]])

In [56]:
points[:-1, :]

tensor([[1., 2.],
        [3., 4.]])

#### 텐서 이름 지정

In [64]:
# 생성할 때 이름 지정
mytensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], names=('batch', 'channel', 'height'))
mytensor.names

('batch', 'channel', 'height')

In [68]:
# 이미 생성된 텐서에 이름 지정
mytensor2 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
mytensor2 = mytensor2.refine_names('batch', 'channel', 'height')
mytensor2.names

('batch', 'channel', 'height')

In [72]:
tensor1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], names=('batch', 'channel', 'height'))
tensor2 = torch.tensor([[[1, 1], [1, 1]], [[1, 1], [1, 1]]], names=('batch', 'channel', 'height'))

result = tensor1 + tensor2
result

tensor([[[2, 3],
         [4, 5]],

        [[6, 7],
         [8, 9]]], names=('batch', 'channel', 'height'))

In [82]:
tensor1 = tensor1.rename(None)
tensor1.names

(None, None, None)

In [84]:
tensor2 = tensor2.rename(batch="dim0", channel="dim1", height="dim2")
tensor2.names

('dim0', 'dim1', 'dim2')

#### 브로드캐스팅

1. 각 tensor는 적어도 하나의 차원을 가진다.
2. 브로드캐스팅을 위해 차원을 비교할 때는 맨 뒤(가장 오른쪽)의 차원부터 시작한다. 
3. 각 차원의 크기는 세 가지 조건 중 하나를 만족해야한다.
	- 두 텐서의 해당 차원의 크기가 같다.
	- 해당 차원의 크기 중 하나가 1이여야 한다.
    - 비교 중인 차원 중 하나가 존재하지 않아야한다. 부족한 차원은 크기가 1로 간주해서 확장한다. 

In [105]:
# a 브로드캐스팅 일어나지 않음 바로 연산 가능
A = torch.tensor([[1, 2, 3], [4, 5, 6]])  
B = torch.tensor([[7, 8, 9], [10, 11, 12]])  
C = A + B
C

tensor([[ 8, 10, 12],
        [14, 16, 18]])

In [107]:
#b 
A = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
B = torch.tensor([[1], [2]])  # Shape: (2, 1)
C = A + B # B가 (2, 3)으로 확장되어 연산
C

tensor([[2, 3, 4],
        [6, 7, 8]])

In [126]:
#c
A = torch.tensor([1, 2, 3])  # Shape: (3)
B = torch.tensor([[4, 5, 6], [7, 8, 9]])  # Shape: (2, 3)
C = A + B  # A가 (2, 3)으로 확장되어 연산
C

tensor([[ 5,  7,  9],
        [ 8, 10, 12]])

In [128]:
# + align_as 사용해보기
tensor1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], names=('batch', 'channel', 'height'))
tensor2 = torch.tensor([[1, 1], [1, 1]], names=('channel', 'height'))
tensor1.shape, tensor2.shape

(torch.Size([2, 2, 2]), torch.Size([2, 2]))

In [130]:
tensor2_aligned = tensor2.align_as(tensor1)

tensor2_aligned.shape, tensor2_aligned.names

(torch.Size([1, 2, 2]), ('batch', 'channel', 'height'))

In [132]:
res = tensor1 + tensor2_aligned
res

tensor([[[2, 3],
         [4, 5]],

        [[6, 7],
         [8, 9]]], names=('batch', 'channel', 'height'))

#### 텐서의 데이터 타입
1. torch.float32 또는 torch.float: 32비트 부동 소수점
2. torch.float64 또는 torch.double: 64비트 부동 소수점
3. torch.float16 또는 torch.half: 16비트 부동 소수점
4. torch.int8: 8비트 정수
5. torch.uint8: 8비트 부호 없는 정수
6. torch.int16 또는 torch.short: 16비트 정수
7. torch.int32 또는 torch.int: 32비트 정수
8. torch.int64 또는 torch.long: 64비트 정수
9. torch.bool: Boolean

In [139]:
a = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
a.dtype

torch.float32

In [141]:
b = torch.tensor([1.0, 2.0, 3.0]).to(torch.float)
b.dtype

torch.float32

/var/folders/t9/qppwntn17hlfp30wqvkm09280000gn/T/ipykernel_28305/3076968323.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  b.storage()


 1.0
 2.0
 3.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 3]

In [153]:
tensor1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], names=('batch', 'channel', 'height'))
sto = tensor1.storage()
sto

 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 8]

In [157]:
sto[1]=4
sto

 1
 4
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 8]

In [159]:
a = torch.ones(3,2)
a.zero_() #텐서 객체에서만 작동 끝이 밑줄로 끝나는거 
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

#### 텐서의 메타데이터

In [164]:
import torch

points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]

print(points[1])

# Storage Offset
print(second_point.storage_offset()) # 텐서의 데이터가 저장된 위치에서 텐서의 첫 번째 요소까지의 오프셋 = 2

# Shape 확인
print(second_point.size()) 

# Stride 확인
print(second_point.stride()) # 다음 요소로 이동하기 위해 건너뛰어야 하는 메모리 위치 수

tensor([5., 3.])
2
torch.Size([2])
(1,)


In [168]:
# 전치
some_t = torch.ones(3, 4, 5)
print(some_t.shape)
transpose_t = some_t.transpose(0, 2)
print(transpose_t.shape)
print(some_t.stride())
print(transpose_t.stride()) 

torch.Size([3, 4, 5])
torch.Size([5, 4, 3])
(20, 5, 1)
(1, 5, 20)


In [170]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [172]:
points_t_cont = points_t.contiguous()
points_t.stride(), points_t_cont.stride()

((1, 2), (3, 1))

In [174]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device="cuda")
points_gpu  = points.to(device="cuda")
# 맥북 이슈로 cuda 사용 불가함

AssertionError: Torch not compiled with CUDA enabled

In [178]:
points = torch.ones(2,3)
np = points.numpy()
np

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [180]:
!pip install h5py